// <auto-generated />
namespace DataAcessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class writer_title_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(writer_title_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202111162338181_writer_title_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
