// <auto-generated />
namespace DataAcessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class wr_img_uzunluk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wr_img_uzunluk));
        
        string IMigrationMetadata.Id
        {
            get { return "202111190850447_wr_img_uzunluk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
