// <auto-generated />
namespace DataAcessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class contact_dateaddded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact_dateaddded));
        
        string IMigrationMetadata.Id
        {
            get { return "202111252244016_contact_dateaddded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
